// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: admin/v1/api.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetHostReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetHostReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHostReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetHostReqMultiError, or
// nil if none found.
func (m *GetHostReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHostReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetHostReqMultiError(errors)
	}

	return nil
}

// GetHostReqMultiError is an error wrapping multiple validation errors
// returned by GetHostReq.ValidateAll() if the designated constraints aren't met.
type GetHostReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHostReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHostReqMultiError) AllErrors() []error { return m }

// GetHostReqValidationError is the validation error returned by
// GetHostReq.Validate if the designated constraints aren't met.
type GetHostReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHostReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHostReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHostReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHostReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHostReqValidationError) ErrorName() string { return "GetHostReqValidationError" }

// Error satisfies the builtin error interface
func (e GetHostReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHostReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHostReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHostReqValidationError{}

// Validate checks the field values on GetHostResp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetHostResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetHostResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetHostRespMultiError, or
// nil if none found.
func (m *GetHostResp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetHostResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetHostRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetHostRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetHostRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetHostRespMultiError(errors)
	}

	return nil
}

// GetHostRespMultiError is an error wrapping multiple validation errors
// returned by GetHostResp.ValidateAll() if the designated constraints aren't met.
type GetHostRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetHostRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetHostRespMultiError) AllErrors() []error { return m }

// GetHostRespValidationError is the validation error returned by
// GetHostResp.Validate if the designated constraints aren't met.
type GetHostRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetHostRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetHostRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetHostRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetHostRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetHostRespValidationError) ErrorName() string { return "GetHostRespValidationError" }

// Error satisfies the builtin error interface
func (e GetHostRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetHostResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetHostRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetHostRespValidationError{}

// Validate checks the field values on HostData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *HostData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HostData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in HostDataMultiError, or nil
// if none found.
func (m *HostData) ValidateAll() error {
	return m.validate(true)
}

func (m *HostData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetName()) < 1 {
		err := HostDataValidationError{
			field:  "Name",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Ip

	// no validation rules for Status

	// no validation rules for LastId

	// no validation rules for LastTime

	if len(errors) > 0 {
		return HostDataMultiError(errors)
	}

	return nil
}

// HostDataMultiError is an error wrapping multiple validation errors returned
// by HostData.ValidateAll() if the designated constraints aren't met.
type HostDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HostDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HostDataMultiError) AllErrors() []error { return m }

// HostDataValidationError is the validation error returned by
// HostData.Validate if the designated constraints aren't met.
type HostDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HostDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HostDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HostDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HostDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HostDataValidationError) ErrorName() string { return "HostDataValidationError" }

// Error satisfies the builtin error interface
func (e HostDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHostData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HostDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HostDataValidationError{}
